#development:
  adapter: myaql
  encoding: unicode
  host: localhost
  database: 
  username: 
  password: 

staging:
  adapter: mysql 
  encoding: unicode
  host:     
  database: 
  username: 
  password:


production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: mysql
  encoding: unicode
  host:    
  database: 
  username:
  password: 
